language: c
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update
install:
  - sudo apt-get install build-essential gcc-arm-none-eabi
env:
  - EXAMPLE=blink
  - EXAMPLE=crc
  - EXAMPLE=usb-serial-loopback
script:
  - cd examples/$EXAMPLE
  - make